const menu: any = [{
  id: '1',
  icon: 'icon-dashboard',
  path: '/dashboard',
  title: '首页',
  main: true,
  read: true,
}, {
  id: '7',
  icon: 'icon-business-service',
  path: '/business',
  title: '业务服务',
  main: true,
  read: true,
}, {
  id: '2',
  icon: 'icon-resource',
  title: '物理资源',
  main: true,
  read: true,
  children: [
    {id: '20', icon: 'icon-data-center', path: '/resource/data-center', title: '机房', read: true, create: true, update:　true, delete: true},
    {id: '21', icon: 'icon-cabinet', path: '/resource/cabinet', title: '机柜', read: true, create: true, update: true, delete: true},
    {id: '22', icon: 'icon-pmserver', path: '/resource/pm-server', title: '物理机', read: true, create: true, update:　true, delete: true},
    {id: '23', icon: 'icon-server', path: '/resource/server', title: '服务器', read: true, create: true, update:　true, delete: true},
    {id: '24', icon: 'icon-network-devices', path: '/resource/network-devices', title: '网络设备', read: true, create: true, update:　true, delete: true},
    {id: '25', icon: 'icon-manufacturer', path: '/resource/manufacturer', title: '厂商信息', read: true, create: true, update:　true, delete: true},
    {id: '26', icon: 'icon-maintain-record', path: '/resource/maintain-record', title: '维修记录', read: true, create: true, update:　true, delete: true},
  ],
}, {
  id: '4',
  icon: 'icon-attribute',
  title: '服务资源',
  main: true,
  read: true,
  children: [
    {id: '41', icon: 'icon-zookeeper', path: '/attribute/zookeeper', title: 'Zookeeper', read: true, create: true, update:　true, delete: true},
    {id: '42', icon: 'icon-haproxy', path: '/attribute/haproxy', title: 'Haproxy', read: true, create: true, update:　true, delete: true},
    {id: '43', icon: 'icon-nginx', path: '/attribute/nginx', title: 'Nginx', read: true, create: true, update:　true, delete: true},
    {id: '44', icon: 'icon-lvs', path: '/attribute/lvs', title: 'LVS', read: true, create: true, update:　true, delete: true},
    {id: '45', icon: 'icon-pdydios', path: '/attribute/mq', title: 'MQ', read: true, create: true, update:　true, delete: true},
    {id: '46', icon: 'icon-mysql', path: '/attribute/mysql', title: 'MySQL', read: true, create: true, update:　true, delete: true},
    {id: '47', icon: 'icon-redis', path: '/attribute/redis', title: 'Redis', read: true, create: true, update:　true, delete: true},
    {id: '48', icon: 'icon-java', path: '/attribute/java', title: 'Java', read: true, create: true, update:　true, delete: true},
  ],
}, {
  id: '7',
  icon: 'icon-rmon-collect',
  title: '监控总览',
  main: true,
  read: true,
  children: [
    {id: '71', icon: 'icon-rmon-overview', path: '/rmon/overview', title: '汇总监控', read: true, create: true, update:　true, delete: true},
    {id: '72', icon: 'icon-rmon-search', path: '/rmon/search', title: '域名搜索', read: true, create: true, update:　true, delete: true},
    {id: '73', icon: 'icon-rmon-domain', path: '/rmon/domain', title: '重点域名', read: true, create: true, update:　true, delete: true},
  ],
}, {
  id: '3',
  icon: 'icon-deploy',
  title: '资源配置',
  main: true,
  read: true,
  children: [
    {id: '31', icon: 'icon-cpu', path: '/deploy/cpu', title: 'cpu', read: true, create: true, update:　true, delete: true},
    {id: '32', icon: 'icon-memory', path: '/deploy/memory', title: '内存', read: true, create: true, update:　true, delete: true},
    {id: '33', icon: 'icon-disk', path: '/deploy/disk', title: '硬盘', read: true, create: true, update:　true, delete: true},
    {id: '34', icon: 'icon-raid', path: '/deploy/raid', title: 'Raid', read: true, create: true, update:　true, delete: true},
  ],
}, {
  id: '6',
  icon: 'icon-account-setting',
  title: '账号设置',
  main: true,
  read: true,
  children: [
    {id: '61', icon: 'icon-company', path: '/userinfo/company', title: '公司信息', read: true, create: true, update:　true, delete: true},
    {id: '62', icon: 'icon-account', path: '/userinfo/account', title: '账号管理', read: true, create: true, update:　true, delete: true},
    {id: '63', icon: 'icon-project', path: '/userinfo/pro-team', title: '项目组', read: true, create: true, update:　true, delete: true},
    {id: '64', icon: 'icon-account', path: '/userinfo/power-system', title: '权限管理', read: true, create: true, update:　true, delete: true},
    // {id: '64', icon: 'icon-pdydios', path: '/userinfo/pro-member', title: '项目成员'},
    {id: '65', icon: 'icon-pdydios', path: '/userinfo/user-profile', title: '用户信息', read: true, create: true, update:　true, delete: true},
  ],
}];
export default menu;
